"""
Module Doc String
"""

APATHY = [
    "I don't want to do anything",
    "there's nothing I want to do",
    "I have no motivation",
    "I can't get motivated",
    "No motivation to do anything",
    "I want to do absolutely nothing",
    "I can't motivate myself",
    "Nothing is fun anymore",
    "everything frustrates me lately",
    "not in the mood to laugh or smile",
    "I don't enjoy anything",
    "I enjoy nothing.",
    "I don't desire anything",
    "my motivation is so low",
    "Nothing excites me anymore",
    "I don't have the will to do anything",
    "I'm losing interest in everything",
    "My lack of motivation and ambition",
    "I'm not interested",
    "I can no longer get joy from anything",
    "I don't yearn anything",
    "I have no hobbies",
    "I don't enjoy my hobbies",
    "I'm unable to start new hobbies",
    "I lack enthusiasm",
    "I have no passion",
    "I have no desire to do anything",
    "I have no drive",
    "I'm unmotivated",
    "Everything seems lame",
    "I find no enjoyment in things I used to enjoy.",
    "nothing is exciting",
    "I want hobbies again",
    "I want passion",
    "I want to be able to enjoy again",
    "everything is boring now",
    "i have no interest in this",
    "I don't have ambitions",
    "I have no career goals",
    "I don't feel like I'm enjoying my",
    "None of them seem appealing to me anymore",
    "I'm not passionate for anything",
]
