"""
Module Doc String
"""

LABELING = [
    "I'm a worthless nothing",
    "I'm a horrible person",
    "I'm a piece of shit",
    "I feel inadequet",
    "I'm such a fat lump",
    "I'm a fat lump of lard",
    "how ugly I am compared to",
    "i'm an awful human being.",
    "how fat I am compared to",
    "I can't help but feel like a disappointment and a failure to my friends and parents.",
    "I'm so disgusted with myself.",
    "I realized I was also a rather terrible person.",
    "I'm disspoiment to my mother.",
    "i feel so fucking fat it\u2019s insane.",
    "My life is such a waste",
    "I feel completely ugly compared to my sister.",
    "I must be the worst person in the world because of the way people treat me.",
    "I feel like I'm a freak",
    "I feel like a terrible person for having these thoughts.",
    "I feel like I'm a terrible parent.",
    "I felt like an inconsiderate piece of shit ",
    "I'm pathetic.",
    "I am ashamed of who I am ",
    "I feel like I'm the worst person in the world.",
    "I must have sounded so ignorant and bitter and intolerant and pathetic to him.",
    "I feel like I'm a alien",
    "I'm pretty much useless",
    "I can't impress anybody",
    "I'm really unpleasant",
    "I'm just a total mess",
    "I have no talent",
    "I have no skills",
    "I suck at everything",
    "I suck at my current job",
    "I suck at school",
    "I suck at sports",
    "I'm not as intelligent",
    "I don't do anyone any good",
    "I'm so disgusting",
    "I feel so disgusting",
    "I have nothing to offer",
    "I have nothing in my life",
    "I suck at everything I try",
    "I fail at everything I try",
    "I'm incapable",
    "I'm too much of a pussy",
    "I'm retarded",
    "I'm the absolute worst",
    "I don't belong here",
    "I'm unbearable to be around",
    "I am unlikable",
    "I am useless to society",
    "I am stupid",
    "I'm literally a waste of space",
    "I'm literally a waste of time",
    "I am a pig",
    "I am a slob",
    "I am a fool",
    "I am a dunce",
    "I am a idiot",
    "I feel useless",
    "I feel worthless",
    "I feel unwanted",
    "I don't belong anywhere",
    "I'm a fucking failure",
    "I fail at everything I do",
    "I am incredibly ugly",
    "I am so fat",
    "I am such a loser",
    "I am pathetic",
    "I feel pathetic",
    "I'm a weirdo",
    "I'm hideous",
    "I'm hopeless",
    "I'm broken",
    "I'm unstable",
    "I'm good for nothing",
    "I'm despicable",
    "I'm a lousy degenerate",
    "I'm not talented in anything",
    "I don't deserve anything",
    "It's obviously because I'm nasty",
    "I end up looking like a dumbass",
    "I've completely failed on everything so far",
    "I am so pathetic",
    "I feel petty and pathetic",
    "I know I'm stupid",
    "I'm just a lazy idiot",
    "because how pathetic I am",
    "I feel as though I'm incapable",
    "I thought I was incredibly ugly and fat",
    "I am incapable of that",
    "I'm not deserving of a relationship",
    "I'm not deserving of a job",
    "I'm not deserving of happiness",
    "Parents told me I'm stupid",
    "I'm unstable internally",
    "how fucking stupid I am",
    "I'm a jackass",
    "I'm a freak",
    "I never fulfilled anything",
    "I'm a loner",
    "Nobody wants to be around me",
    "I'm a little bitch",
    "by being the little bitch I am",
    "I never accomplished anything",
    "I'm a wreck",
    "I'm a fucking wreck",
    "I'm not good at talking to girls",
    "I've never been good at",
    "I'm terrible at talking to people",
    "I'm terrible at my job",
    "I can't stand looking at the mirror",
    "I'm a nobody",
    "I feel very inadequate",
    "I'm not good enough for her",
    "I'm not good enough for my parents",
    "I'm so selfish",
    "I'm a selfish son of a bitch",
    "I'm feeling useless",
    "I fail at everything I do",
    "I'm a horrible person",
]
