"""
MITI Code seeds
"""

MITI_SEEDS = {
    "Persuade": [
        "Would that be something you might be interested in?",
    ],
    "Seeking_Collaboration": [
        "Is it ok if I",
        "Would you like to set a goal",
        "If it's ok with you",
        "If that's something you'd like to do",
        "If you want you can try one or two",
        "Okay, well if it's alright with you,",
        "So that might be something that you find helpful",
        "if you wanted to set a goal for yourself",
        "if it's alright with you I'd like to talk a little bit about your values ",
        "if you wouldn't mind choosing maybe 2 or 3 things off that list things",
        "if it's something that you're interested in doing ",
    ],
    "Autonomy": [
        "It's completely up to you",
        "find something that works for you",
        "that's totally up to you",
        "I'm just going to leave this with you and it's up to you",
        "You're welcome to do this or not",
        "Whatever works for you",
        "if you want to it's up to you",
        "it's up to you if not that's okay as well",
        "what works for you might not work for someone else",
        "What works for them might not work for you",
    ],
    "Simple_Reflection": [
        "so it sounds like it's a problem",
        "so it sounds like that worries you",
        "so what I'm hearing is that",
        "it meant a lot to you",
        "That's stressing you out",
        "That's bothering you",
        "and so you're worried about it",
        "so if I understand you correctly",
        "That makes sense to me",
    ],
    "Affirm": [
        "Well done , you've done great",
        "So far you're off to a great start",
        "You're doing a great job",
        "You should be proud of yourself",
        "I appreciate your honesty",
        "It sounds like you're doing pretty well",
        "You're right on the mark each day",
        "You've come a long way.",
        "I'm glad you feel good about your accomplishment",
        "You're perfect with your adherence",
        "That's from all your hard work congratulations",
    ],
    "Question": [
        "Is there anything else that you can think of?",
        "On a scale from one to ten, what would you say is",
        "What are your thoughts about that?",
        "How has that been going for you?",
        "On a scale from to, how important is it for you",
        "And why would you say not a ten?",
        "Well, was there anything you found helpful about our session today?",
        "So what makes that so important for you?",
        "Is there a goal you would like to set?",
        "with 1 being not important to 10 being very important, what would you give",
        "Why is being healthy important for you?",
        "So what are your thoughts on",
        "Ok so tell me more about that",
        "Why an 8 and not a 4?",
    ]
}
