"""
MITI Code seeds
"""

MITI_SEEDS = {
    "Persuade": [
        "Would that be something you might be interested in?",
    ],
    "Seeking_Collaboration": [
        "Is it ok if I",
        "Would you like to set a goal",
        "If it's ok with you",
        "If that's something you'd like to do",
        "If you want you can try one or two",
        "Okay, well if it's alright with you,",
        "So that might be something that you find helpful",
        "if you wanted to set a goal for yourself",
        "if it's alright with you I'd like to talk a little bit about your values ",
        "if you wouldn't mind choosing maybe 2 or 3 things off that list things",
        "if it's something that you're interested in doing ",
    ],
    "Autonomy": [
        "It's completely up to you",
        "It is totally up to you whether you quit",
        "It's your decision",
        "find something that works for you",
        "that's totally up to you",
        "I'm just going to leave this with you and it's up to you",
        "You're welcome to do this or not",
        "Whatever works for you",
        "if you want to it's up to you",
        "it's up to you if not that's okay as well",
        "what works for you might not work for someone else",
        "What works for them might not work for you",
    ],
    "Simple_Reflection": [
        "so it sounds like it's a problem",
        "so it sounds like that worries you",
        "so what I'm hearing is that",
        "it meant a lot to you",
        "That's stressing you out",
        "That's bothering you",
        "and so you're worried about it",
        "so if I understand you correctly",
        "That makes sense to me",
    ],
    "Affirm": [
        "Well done , you've done great",
        "So far you're off to a great start",
        "You're doing a great job",
        "You should be proud of yourself",
        "I appreciate your honesty",
        "It sounds like you're doing pretty well",
        "You're right on the mark each day",
        "You've come a long way.",
        "I'm glad you feel good about your accomplishment",
        "You're perfect with your adherence",
        "That's from all your hard work congratulations",
        "You've made a lot of progress so far",
        "Thank you for coming today.",
        "I appreciate you telling me that",
        "I appreciate your honesty",
        "I've enjoyed talking with you today.",
        "You've succeeded through some difficult changes in the past",
        "You've had success in the past",
        "That's a good idea.",
        "Good for you",
    ],
    "Question": [
        "Is there anything else that you can think of?",
        "On a scale from one to ten, what would you say is",
        "What are your thoughts about that?",
        "How has that been going for you?",
        "On a scale from to, how important is it for you",
        "And why would you say not a ten?",
        "Well, was there anything you found helpful about our session today?",
        "So what makes that so important for you?",
        "Is there a goal you would like to set?",
        "with 1 being not important to 10 being very important, what would you give",
        "Why is being healthy important for you?",
        "So what are your thoughts on",
        "Ok so tell me more about that",
        "Why an 8 and not a 4?",
        "Tell me more about your",
        "Tell me more.",
        "I'd like to know more about",
        "I wonder why you feel that way",
        "How does that make you feel?",
        "What do you want to do about your drug use?",
        "Tell me about your drinking.",
        "You want to change, but are not sure how to?",
        "What do you want to do about your drinking?",
        "How might you be able to do that?",
        "Do you want to change?",
        "So change is important to you?",
        "On a scale of 1 to 10, how much do you want to change?",
        "Could you tell me what you think about change?",
        "How much do you want to change?",
    ],
    "Confrontation": [
        "You're lucky you didn't kill yourself or somebody else.",
        "Look, I'm an ER doctor and I think I know when somebody's an alcoholic",
        "I think you have a serious drinking problem and you better straighten it out.",
        "Do not drink and drive.",
        "You've got to learn to take responsibility.",
        "Now's the time to quit.",
        "It's now or never.",
        "You knew this would happen and you did it anyway.",
        "Don't you understand how this is affecting your health?",
    ],
    "Advise_With_Permission": [
        "Would it be all right if I suggested something?",
        "Do you mind if I tell you how ",
        "We could try brainstorming to come up with ideas about quitting if you'd like",
        "This may or may not work for you, but I recommend",
        "I'd like to get your thoughts, but we can try to",
    ],
    "Advise_Without_Permission": [
        "Consider doing this next time.",
        "You could ask your friends not to drink around you.",
        "You should really keep doing what you're doing.",
        "After this session, you should write all these things down.",
        "I recommend that you ",
        "Just going cold turky is the best way to give up",
    ],
    #"Facilitating": [
    #    "Mmm.",
    #    "Mmhmm",
    #    "uh huh",
    #    "Okay",
    #    "Good",
    #    "Right",
    #],
    "Filler": [
        "So what brings you to see us today?",
        "Hi Theodore. Nice to see you.",
        "How are things going?",
    ],
    "Direct": [
        "Don't say that!",
        "Get out there and find a job",
        "You need to watch this video",
        "I want you to give it a try.",
        "You've got to stop drinking",
        "You must have more respect for yourself",
        "You can't keep smoking",
    ],
    "Raise_Concern": [
        "I'm worried about your plan to ",
        "Is it ok if I tell you a concern that I have about that?",
        "It worries me",
        "I'm a little worried that you're ",
    ],
    "Structure": [
        "What we normally do is start by asking you about",
        "Now I'd like to talk with you about ",
        "In this study I'll meet you twice a month",
        "We give this form for everyone to fill out",
        "Why don't we start by ",
    ],
    #"Patient_Change_Language": [
    #    "I am going to stop smoking tomorrow",
    #    "I'll never drink and drive.",
    #    "One thing I could try is cutting down on",
    #    "Maybe I can try to wait 10 minutes next time",
    #    "I could try that instead of",
    #],
    #"Patient_Desire": [
    #    "I want to quit doing drugs",
    #    "I want to lose weight",
    #    "I want to change",
    #    "I don't want to live like this anymore",
    #    "I want to eat healthier",
    #],
    "Information": [
        "Previous studies show that",
        "There's been a lot of research on",
        "It is common knowledge that",
        "According to researchers",
    ],
}
