"""
Module Doc String
"""

SCARED = [
    "I feel scared to",
    "I'm so scared.",
    "I\u2019ve become scared of letting people in.",
    "I am so scared.",
    "I have just been too scared and nervous to do anything significant.",
    "I feel fear",
    "I feel scared of ",
    "I am terrified",
    "I am beyond scared",
    "I'm feeling nervous about",
    "I feed on edge because",
    "I'm scared something terrible is going to happen",
    "I was so scared to",
    "I'm scared to speak my mind",
    "I'm afraid of",
    "I get panic attacks",
    "I have so much fear",
    "I'm always afraid of",
    "I'm always afraid that",
    "I'm always terrified that I'm going to mess up and that it will make me a bad person.",
    "I feel like I'm always afraid that everyone else hates me just as much as I hate myself.",
    "I'm terrified of losing him and I'm always scared that he doesn't like to be around me.",
    "I've had a few panic attacks",
    "I fear that",
    "I get just as panicked about",
    "I'm utterly terrified of failure",
    "I'm utterly terrified of ",
    "I'm terrified of because of",
    "I'm afraid that my ",
    "cycles of panic about",
    "I sometimes have anxiety attacks in the ",
    "having panic attacks",
    "I'm scared about my future",
    "I'm scared but I also",
    ", but i 'm so terrified",
    'Honestly , I ’m also scared',
    "because of my fear of",
    "I 'm kind of scared but",
    'I have so much fear ',
    'I ’m afraid I',
    'I was scared and',
    "again but I 'm so scared to",
    'but I just to scared to',
    "due to my crippling fear",
    "I 've had a few panic attacks",
    "I 'm always terrified that",
    "I feel like I 'm always afraid that",
    "Still , I 'm always so so afraid",
    'because I was scared of',
    "I 'm actually a little scared to",
    "because I 'm afraid the",
    'Just I was super scared without',
    'I had another panic attack',
    'that was my main fear',
    'can stop getting scared like',
    'I ’m honestly just afraid I',
    'And I still am scared',
    "wake up in panic attacks",
    "get in this cycle of panic",
    "I am frightened of",
    "I am fearful about",
    "I'm nervous that",
    "I am petrified",
    "I was frantic",
    "I was shaky with fear"
    "I was shitting bricks",
    "I'm really worried about"
    "I can't stop worrying about",
    "I can't control my worries",
    "I'm constantly worrying about",
    "I am worried about everything",
    "I'm worried about what's happening",
    "I'm very worried about taking",
    "I'm worried though",
    "I'm concerned about",
]
