"""
Module Doc String
"""

SELF_BLAME = [
    "I still feel guilty about it, even though it\u2019s been years.",
    "beating myself up for my own mistakes",
    "because of my short comings",
    "because of my shortcomings",
    "because of my mistakes",
    "because of my errors",
    "because of my ignorance",
    "because of my stupidity",
    "I blame myself for things that ",
    "And blaming myself for everything.",
    "but it was my fault making my .",
    "No one to blame but me.",
    "No one to blame but myself.",
    "it's my own fault because ",
    "they blame me for their divorce.",
    "Is it the drugs to blame or me ",
    "But I can only blame myself for that.",
    "and I would only blame myself.",
    "I know it was my fault",
    "she kept telling me that it was all fault ",
    "and I blame my extreme bad luck ",
    "and I just know that this is all my fault and I've brought it on myself.",
    "I've brought all it on myself.",
    "I blame my self for everything which I should, because lots of things are all my fault",
    "I blame my self for everything ",
    "because lots of things are all my fault",
    "I have only myself to blame",
    "in all fairness is my fault",
    "it's probably my fault",
    "I sort of blamed myself",
    "I can blame myself",
    "I want to make sure no blame is put on them because this is my fault.",
    "I know it was my fault, ",
    "so entirely my fault.",
    "is my own fault",
    "this sadness is my own fault",
    "this pain is my own fault",
    "this loneliness is my own fault",
]
