"""
Module Doc String
"""

SUBSTANCE_ABUSE = [
    "I've been in rehab for years",
    "I'm recovering from my addiction to",
    "I've been addicted to weed",
    "on so many drugs right now",
    "I've started smoking and started drinking to try to cope",
    "degeneracy of sex drugs and alcohol",
    "Usually smoke weed almost everyday",
    "usually just smoke a ton of weed",
    "prescription drug overdose and caused",
    "I've been addicted to drugs",
    "I've been addicted to alcohol",
    "I was an alcoholic",
    "I went to rehab ",
    "I have substance abuse problems",
    "I've abused substances in the past",
    "I survived over dosage",
    "I survived overdose of drugs",
    "I OD-ed on drugs",
    "I quit drugs",
    "I quit taking drugs",
    "I drink every night",
    "I get drunk every night",
    "I get high every night",
    "I am with a drinking problem",
    "I have an addiction problem",
    "I drink about shots a night",
    "I drink about ten shots every night",
    "I smoke a serious amount of pot",
    "I drink a serious amount of alcohol",
    "I get drunk every night",
    "I get fucked up every night",
    "I drink a whole bottle every night",
    "Opioids aren't doing this",
    "Taking much higher doses of",
    "I use pot to curb side effects",
    "I use opioids to make myself relax",
    "I'm chugging wine to get through this",
    "I'm chugging vodka to get through this",
    "I've nbeen using Kratom, which is an opioid",
    "I've been taking adderall for years",
    "Smoking weed is the only thing that brings me joy",
    "I smoked weed, cigarettes, and vape",
    "I drink all my problems away",
    "I overdosed on Zoloft",
    "I overdosed on Lexapro before",
    "I overdosed on cocaine",
    "a majority of them were SSRI overdoses",
    "quitting drugs has been a challenge",
    "I've quit all my drug uses",
    "Should I keep taking adderall",
    "All I want to do is smoke week",
    "All I want to do is drink",
    "All I want to do is get high",
    "All I want to do is get drunk",
    "I used to smoke weed to fill in the pain",
    "I'm not ready to become a deeper addict",
    "I was heavily addicted through",
    "I am a substance abuser",
    "I'm spending all my money on drugs",
    "I used to spend all my money on drugs",
    "I resorted to daily heavy drinking",
    "I spent all my money on oxycontin",
    "I'm addicted to oxy",
    "I'm addicted to oxycontin",
    "I'm addicted to nicotine",
    "I'm addicted to drugs that make me feel good",
    "I've had several overdoses on ",
    "grew an obsession with many drugs",
    "drink heavily on a regular basis",
    "drink heavily on a daily or weekly basis",
    "I need to avoid abusing drugs and alcohol",
    "I am a recovering alcoholic",
    "I am a recovering addict",
    "I'm becoming a meth addict",
    "I smoke cannabis until I calm down",
    "I am working on being sober",
    "I am trying to be sober",
    "I cannot do sobriety",
    "Any pills I find I take",
    "I pop pills on a regular basis",
    "Drinking is a huge part of my life",
    "I drink and don't know how to stop",
    "I don't know how to stop drinking",
    "I smoke and don't know how to stop",
    "I don't know how to stop smoking",
    "I'm going to spend all my money on vape juice",
    "I'm going to spend all my money on alcohol",
    "I'm going to spend all my money on marijuana",
    "I'm going to spend all my money on drugs",
    "I started smoking cigarettes and weed more",
    "I stopped smoking pot nearly a year ago",
    "my mom is also a drug addict",
    "When I drink I feel more liberated",
    "drugs and alcohol have kept me from seeking help",
    "not smoking weed is hard enough",
    "I drown my feelings with alcohol and cannabis",
    "I fell in love with marijuana",
    "I stopped smoking wee and ciagerettes",
    "I stopped drinking and everything",
    "I am 30 days sober",
    "I am 100 days sober",
    "I am 3 years sober",
    "she developed a drug problem",
    "I stopped smoking weed and ciagerettes totally",
    "He is a recovering alcoholic",
    "Getting drunk every night, thinking about drugs",
    "I've spiraled back to alcoholism",
    "time to numb the pain with alcohol",
    "I'm gonna smoke lots of weed and pass out",
]
