"""
Module Doc String
"""

SUICIDAL = [
    "I should just kill myself",
    "I don't want to live",
    "I want to die",
    "why bother living anymore",
    "I don't see a reason to live",
    "I don't want to be conscious",
    "I want to disappear",
    "I should do the world a favor and disappear",
    "I'm too scared to kill myself",
    "I'm going to cut myself",
    "I'm going to hang myself",
    "I want to give up on life",
    "I think it would be better if I could just disappear",
    "I think it would be better if I just died",
    "I tried to kill myself before",
    "i took pain killers to kill myself",
    "I slit my wrist to",
    "There is not a day where suicidal thoughts don't come to mind",
    "the suicidal thoughts won't leave",
    "suicidal thoughts come and go",
    "I had constant severe suicidal thoughts",
    "I looked up how to commit suicide",
    "I don't belong on this earth",
    "I'm not afraid to die",
    "I almost decided to slit my throat",
    "please kill me",
    "life is not worth living anymore",
    "I don't really want to be alive",
    "I don't want to exist",
    "I want to cut myself",
    "I want to hang myself",
    "I cut myself with a razor",
    "why should I exist?",
    "why shouldn't I kill myself?",
    "end this pain by killing myself", 
    "I could kill myself",
    "I never thought about suicide but I'm starting to consider it",
    "I don't feel like living",
    "my life is not worth living",
    "I keep having suicidal thoughts",
    "think about hanging myself over this",
    "I have a knife with me and cut myself",
    "I want to hurt myself",
    "I intend to kill myself",
    "I'm not siucidal but I don't mind dying",
    "questioning if my life is worth living it",
    "I would highly consider killing myself if",
    "I'm thinking of ending my life",
    "I couldn't hang myself",
    "I tried overdosing with pills but",
    "thoughts of a noose wrapped around my neck",
    "consider physical suicide seriously",
    "I am suicidal",
    "I feel the need to cut myself",
]
